# Generated by Django 4.0.4 on 2022-07-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
                ('birth_mark', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='missing_people_images')),
                ('date_missing', models.DateField(null=True)),
                ('place_seen_last_time', models.TextField()),
            ],
        ),
    ]
