# Generated by Django 4.0.4 on 2022-07-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='date_missing',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='birth_mark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='image',
            field=models.ImageField(upload_to='missing_people_images'),
        ),
    ]
