# Generated by Django 4.0.4 on 2022-07-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0002_remove_missingperson_date_missing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='date_missing',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
