# Generated by Django 4.0.4 on 2022-07-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosmessage',
            name='location',
        ),
        migrations.AddField(
            model_name='sosmessage',
            name='maps_location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='MilitarySos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sos_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.sosmessage')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sos_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.sosmessage')),
            ],
        ),
    ]
